// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8ypOAapgSjc63q3cMtTUEArF3Nh9WCw',
    appId: '1:908937495731:web:fed7f1d47a935eaf3d1cc6',
    messagingSenderId: '908937495731',
    projectId: 'jp-loki-boardgame-dev',
    authDomain: 'jp-loki-boardgame-dev.firebaseapp.com',
    storageBucket: 'jp-loki-boardgame-dev.firebasestorage.app',
    measurementId: 'G-YC1SK60M4J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFGijd6hFaMJbMIj-1pNBU3u2-wz9yUNI',
    appId: '1:908937495731:android:de8c2d0ef44dc4893d1cc6',
    messagingSenderId: '908937495731',
    projectId: 'jp-loki-boardgame-dev',
    storageBucket: 'jp-loki-boardgame-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9fAMBmWM7JUWOpxbu0D0wW-p_r9Is9H4',
    appId: '1:908937495731:ios:de65a69c580792633d1cc6',
    messagingSenderId: '908937495731',
    projectId: 'jp-loki-boardgame-dev',
    storageBucket: 'jp-loki-boardgame-dev.firebasestorage.app',
    iosBundleId: 'com.example.boardgame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9fAMBmWM7JUWOpxbu0D0wW-p_r9Is9H4',
    appId: '1:908937495731:ios:de65a69c580792633d1cc6',
    messagingSenderId: '908937495731',
    projectId: 'jp-loki-boardgame-dev',
    storageBucket: 'jp-loki-boardgame-dev.firebasestorage.app',
    iosBundleId: 'com.example.boardgame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDX8ypOAapgSjc63q3cMtTUEArF3Nh9WCw',
    appId: '1:908937495731:web:4d65627f0e84e1ef3d1cc6',
    messagingSenderId: '908937495731',
    projectId: 'jp-loki-boardgame-dev',
    authDomain: 'jp-loki-boardgame-dev.firebaseapp.com',
    storageBucket: 'jp-loki-boardgame-dev.firebasestorage.app',
    measurementId: 'G-L0DGNP9ZLR',
  );
}
